using System.Collections.Generic;

namespace Bacchus.Model
{
    /// <summary>
    /// Marque class contains the methods to manage the Marque objects.
    /// </summary>
    class Marque
    {
        public string Name { get; set; }

        /// <summary>
        /// Confort constructor of the class, takes MarqueName in param and instantiates the object.
        /// </summary>
        /// <param name="MarqueName"></param>
        public Marque(string MarqueName)
        {
            this.Name = MarqueName;
        }

        /// <summary>
        /// Override Equals to compare Marque objects
        /// </summary>
        /// <param name="Marque"></param>
        /// <returns>true if same, else false.</returns>
        public override bool Equals(object Marque)
        {
            if (Marque == null)
            {
                return false;
            }
            if (!(Marque is Marque))
            {
                return false;
            }
            return (Name == ((Marque)Marque).Name);
        }

        /// <summary>
        /// Redefinition of the ToString method.
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return Name;
        }

        /// <summary>
        /// autogenerated gethashcode method.
        /// </summary>
        /// <returns></returns>
        public override int GetHashCode()
        {
            return 539060726 + EqualityComparer<string>.Default.GetHashCode(Name);
        }

      
    }
}
